### ISSUE TITLE
Date.UTC should keep working with Timecop installed

### ISSUE THREAD

**Issue by rhunter** [jamesarosen/Timecop.js#13]
Javascript's timezone handling isn't great, but [Date.UTC](https://developer.mozilla.org/en/JavaScript/Reference/Global_Objects/Date/UTC) at least provides some way to create a date that isn't attached to an arbitrary and uncontrollable "local time".

`Timecop.MockDate.UTC = Timecop.NativeDate.UTC`

**Comment by jamesarosen** [comment]
I can't quite figure out whether it should return a `Date` or a `MockDate`. If you're time travelling and you ask for `Date.UTC(...)` (which is really `MockDate.UTC` since you're in your Delorean), is there any reason to return a `MockDate`?

**Comment by rhunter** [comment]
I think the functionality would be identical right now.

Although... If it were possible to travel to a different timezone then I
guess MockDate.UTC would have to be a MockDate.
On Dec 9, 2011 1:44 PM, "James Rosen" <
reply@reply.github.com>
wrote:

**Comment by adamhooper** [comment]
Date.UTC() returns a Number. The number doesn't change based on your timezone, so Timecop should just pass through to the native implementation.
