### ISSUE TITLE
Integration with Timecop gem and rails?

### ISSUE THREAD

**Issue by jhilden** [jamesarosen/Timecop.js#15]
Hi,

has somebody successfully integrated Timecop.js together with the original Timecop gem and rails before?

We have such code in our acceptance tests (using MiniTest and Capybara):

```
before do
  travel_to 'October 10, 2010'
end

after do
  Timecop.return
end
```

The problem is that our backend code is now behaving differently from our client code (in our case a jquery-ui datepicker) in this test.  Maybe there is a way to inject the right javascript snippets in order to create the same behavior on the client side?

We have a `yield :head` in our application layout.  Maybe this could be used to inject the JS using ActionView::Helpers::CaptureHelper.content_for ?   But this is just a vague idea.

Any thoughts anybody?

**Comment by jamesarosen** [comment]
One idea would be to output a `__timecop_now__` JS global and automatically travel to it. That leaves open the question of travel vs. freeze, so perhaps `__timecop_init__ = [ 'travel', "2005-07-11" ];` would work better.

I suppose we could add some Ruby code (a Rack middleware?) to the project that automatically outputs that global to HTML pages.

**Comment by jamesarosen** [comment]
@jhilden are you still interested in this?

**Comment by jhilden** [comment]
Actually I have moved on from the project that this would have been useful for, so I guess there is no current demand.
