### ISSUE TITLE
Date.now() should work

### ISSUE THREAD

**Issue by jwark** [jamesarosen/Timecop.js#21]
Date.now() does not appear to be implemented.  I had a quick look but couldn't easily fix it myself.

For more details, see: https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/Date/now

**Comment by jamesarosen** [comment]
Good catch. I wonder whether it should work even if the underlying JavaScript implementation doesn't have it. It would be weird to time travel and suddenly get new functionality. Maybe something like

``` javascript
if ( Timecop.NativeDate.hasOwnProperty('now') ) {
  Timecop.MockDate.now = function() {
    return Timecop.topOfStack().date().getTime();
  }
}
```

That would go in the [`Timecop.MockDate` definition](https://github.com/jamesarosen/Timecop.js/blob/master/lib/MockDate.js#L13).

**Comment by jwark** [comment]
Sounds like a good plan. Are you happy to implement it, or should i create a pull request?

**Comment by jamesarosen** [comment]
I don't mind doing it, but Timecop is a commit-bit project, so if you get a commit merged, you get committer rights.

**Comment by jwark** [comment]
Ok. I'll give it a go!  Thanks.
